language: go
go: 1.8
install: make setup
script: make ci
after_success:
  # - go get github.com/mattn/goveralls
  # - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken="$COVERALLS_TOKEN"
  - test -n "$TRAVIS_TAG" && curl -sL http://git.io/goreleaser | bash
notifications:
  email: false
